language: cpp

matrix:
  include:
  - os: linux
    dist: xenial
    sudo: required
    script:
      - mkdir build
      - cd build
      - cmake ..
      - make

  - os: osx
    osx_image: xcode9
    compiler: clang
    script:
      - mkdir build
      - cd build
      - cmake ..
      - make