language: cpp

matrix:
  include:
  - os: linux
    dist: bionic
    compiler: gcc
    sudo: required
    script:
      - sh Install.sh
      - sh Build.sh

  - os: osx
    osx_image: xcode11
    compiler: clang
    script:
      - sh Install.sh
      - sh Build.sh

  - os: windows
    script:
      - ./Install.bat
      - ./Build.bat

notifications:
  email: false
