language: cpp

matrix:
  include:
  - os: linux
    dist: bionic
    compiler: gcc
    sudo: required
    script:
      - sh scripts/travis_build.sh

  - os: osx
    osx_image: xcode9
    compiler: clang
    script:
      - sh scripts/travis_build.sh