language: cpp

matrix:
  include:
  - os: linux
    dist: bionic
    compiler: gcc
    sudo: required
    script:
      - sh Install_Linux.sh
      - sh Build.sh

  - os: osx
    osx_image: xcode11
    compiler: clang
    script:
      - sh Install_Mac.sh
      - sh Build.sh

  - os: windows
    script:
      - Install_Windows.bat
      - Build.bat

notifications:
  email: false
