language: cpp

matrix:
  include:
  - os: linux
    dist: bionic
    compiler: gcc
    sudo: required
    script:
      - sh Scripts/TravisBuild.sh

  - os: osx
    osx_image: xcode11
    compiler: clang
    script:
      - sh Scripts/TravisBuild.sh

notifications:
  email: false