language: cpp

matrix:
  include:
  - os: linux
    dist: bionic
	compiler: gcc
    sudo: required
    script:
      - sh scripts/traivs_build.sh

  - os: osx
    osx_image: xcode9
    compiler: clang
    script:
      - sh script/travis_build.sh